version: "3.9"

services:
  db:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - DB_URL=postgresql://root:secret@db:5432/simple_bank?sslmode=disable
    depends_on:
      - db
