version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  sqlc:
    image: sqlc/sqlc
