apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplebank-deployment
  namespace: simplebank
  labels:
    app: eks-simplebank
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-simplebank
  template:
    metadata:
      labels:
        app: eks-simplebank
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: simplebank
        image: aseerkt/simplebank:latest
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux