apiVersion: v1
kind: Service
metadata:
  name: simplebank-service
  namespace: simplebank
  labels:
    app: eks-simplebank
spec:
  selector:
    app: eks-simplebank
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080